version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env

  lb:
    build:
      context: .
      dockerfile: Dockerfile.lb
    ports:
      - "3000:3000"
    depends_on:
      - backend
